# Generated by Django 4.2.2 on 2023-07-02 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('descp', models.CharField(max_length=200)),
                ('upd_date', models.DateTimeField()),
                ('code_desc', models.TextField()),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_app.coder')),
            ],
        ),
    ]
