# Generated by Django 4.2.2 on 2023-07-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='upd_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
