# Generated by Django 4.2.2 on 2023-07-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_web_app1', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_web_app1.events'),
        ),
    ]
