# Generated by Django 4.2.1 on 2023-07-22 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_web_app1', '0003_alter_events_options_remove_entry_topic_entry_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
